services:
  - type: worker
    name: repsolver-bot
    runtime: docker
    repo: https://github.com/Nazar069akimbo/repsolver-bot
    branch: main
    plan: free
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: BOTHUB_API_KEY
        sync: false
      - key: ADMIN_ID
        sync: false
      - key: ADMIN_CODE
        sync: false
      - key: FREE_LIMIT
        sync: false
