from . import start_handler
from . import stats_handler
from . import profile_handler
from . import settings_handler
from . import subscribe_handler
from . import referral_handler
from . import solve_handler
from . import admin_handler
from . import leaderboard_handler
from . import help_handler
